name: "Run SAST Scan on SuperMario Game Project"

on:
  push:
    branches:
      - main

jobs:

  sonarqube_sast_scan:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ github.event.repository.name }}"
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: PhuongLam94/gitops-pipeline-supermario-repo
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarqube/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}